### ISSUE TITLE
Instagram Link

### ISSUE THREAD

**Issue by tobias-goertz** [TechLabs-Berlin/radar#1]
Instagram Link does not refer to the actual TechLabs Berlin page.
1!elf

**Comment by tobias-goertz** [comment]
@Shark what about this urgent issue????

**Comment by Shark** [comment]
@tobias-goertz thank you for pointing out this rather embarassing issue. We are always committed to delivering the highest possible quality and would be happy to receive further bug reports from you in the future.

🐴
