### ISSUE TITLE
Improve readme for beginners

### ISSUE THREAD

**Issue by Maxscha** [TechLabs-Berlin/radar#28]
The readme.md is not very helpful in getting a first grasp of the structure, especially since most people will only change the events.

**Comment by KishkinJ10** [comment]
i am a beginner and i am looking to start my open source journey can i contribute in this ?

**Comment by Maxscha** [comment]
Hey @KishkinJ10 ,

Yes we are always happy for help. Maybe you can share a bit on what experience you already have so we can find a suitable task for you and your skill level 👍
